replicaCount: 2
containerPort: 80

image:
  repository: rukevweubio/bitcointrading-app 
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80
  type: ClusterIP

resources: {}
volumeMounts: [] kuebctl
volumes: []

nodeSelector: {}
affinity: {}
tolerations: {}
podAnnotations: {}

ingress:
  enabled: false

