apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitcoin-app.fullname" . }}
  labels:
    {{- include "bitcoin-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  selector:
    {{- include "bitcoin-app.selectorLabels" . | nindent 4 }}
